### ISSUE TITLE
Poster for IKON

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON#3]

**Comment by ckinkeldey** [comment]
Jesse made a draft:
[lndw-2019-ikon.pdf](https://github.com/FUB-HCC/IKON/files/3281963/lndw-2019-ikon.pdf)

**Comment by avvinter** [comment]
[lndw-2019-ikon-REFINED.pdf](https://github.com/FUB-HCC/IKON/files/3285182/lndw-2019-ikon-REFINED.pdf)
