### ISSUE TITLE
Enhance project symbols

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON#5]

**Comment by ckinkeldey** [comment]
![IMG_7255](https://user-images.githubusercontent.com/3234376/68782360-902d1e80-0639-11ea-891e-9849ec2a2478.JPG)

**Comment by ckinkeldey** [comment]
1. simplify and densify project symbol design
2. create design variations with four different symbols (see image)

**Comment by avvinter** [comment]
[IKON-Symbol-New-1.pdf](https://github.com/FUB-HCC/IKON/files/3868393/IKON-Symbol-New-1.pdf)
[IKON-Symbol-New-2.pdf](https://github.com/FUB-HCC/IKON/files/3868394/IKON-Symbol-New-2.pdf)
[IKON-Symbol-New-3.pdf](https://github.com/FUB-HCC/IKON/files/3868395/IKON-Symbol-New-3.pdf)
[IKON-Symbol-New-4.pdf](https://github.com/FUB-HCC/IKON/files/3868396/IKON-Symbol-New-4.pdf)
all symbols as svg:
[Icon-Symbol-New-SVG.zip](https://github.com/FUB-HCC/IKON/files/3868406/Icon-Symbol-New-SVG.zip)

**Comment by avvinter** [comment]
symbol use simulation

1 - cluster as color and research area as symbol
![Interfacedesign-Webinterface-IKON-Development-3-29](https://user-images.githubusercontent.com/44524000/69230734-20aeb600-0b88-11ea-8f76-34f369e39033.png)

2 - cluster as symbol and research area as color
![Interfacedesign-Webinterface-IKON-Development-3-30](https://user-images.githubusercontent.com/44524000/69230764-27d5c400-0b88-11ea-9fb2-773f5a532628.png)

**Comment by jessebenjamin** [comment]
i like the symbols and option 1. can you please "soften" the interior symbols, with rounded corners for example?

currently, i don't know as a user what the symbols are referring to. this should be communicated in the filters i think (e.g., the top level filter should be associated with the symbol).

**Comment by avvinter** [comment]
![Interfacedesign-Webinterface-IKON-Development-3-31](https://user-images.githubusercontent.com/44524000/69237264-953c2180-0b95-11ea-897b-c357596a8578.png)
![Interfacedesign-Webinterface-IKON-Development-3-32](https://user-images.githubusercontent.com/44524000/69237265-953c2180-0b95-11ea-9154-5e3874745334.png)

**Comment by avvinter** [comment]
[Icon-Symbol-New-rounded-SVG.zip](https://github.com/FUB-HCC/IKON/files/3869060/Icon-Symbol-New-rounded-SVG.zip)
